package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/xuri/excelize/v2"
)

// ============================================================================
// IMPORTACAO DE EXCEL DO UNMIXER SEED
// ============================================================================

func importUnmixerSeedExcel() []string {
	fmt.Println()
	fmt.Println("================================================================")
	fmt.Println("  " + t("IMPORTAR EXCEL DO UNMIXER SEED", "IMPORT UNMIXER SEED EXCEL"))
	fmt.Println("================================================================")
	fmt.Println()

	importDir := t("Importar_Seeds", "Import_Seeds")
	if _, err := os.Stat(importDir); os.IsNotExist(err) {
		os.MkdirAll(importDir, 0755)
		fmt.Println(t(
			"  Pasta criada: "+importDir,
			"  Folder created: "+importDir))
		fmt.Println()
		fmt.Println(t(
			"  Copie os arquivos Excel (.xlsx) gerados pelo Unmixer Seed",
			"  Copy the Excel files (.xlsx) generated by Unmixer Seed"))
		fmt.Println(t(
			"  para esta pasta e pressione Enter para continuar.",
			"  to this folder and press Enter to continue."))
		fmt.Println()
		getUserInput(t("  Pressione Enter quando estiver pronto...", "  Press Enter when ready..."))
	}

	files, err := filepath.Glob(filepath.Join(importDir, "*.xlsx"))
	if err != nil || len(files) == 0 {
		fmt.Println(t(
			"  [!] Nenhum arquivo .xlsx encontrado na pasta "+importDir,
			"  [!] No .xlsx files found in folder "+importDir))
		return nil
	}

	fmt.Printf(t(
		"  Encontrados %d arquivo(s) Excel:\n",
		"  Found %d Excel file(s):\n"), len(files))
	fmt.Println()

	var allSeeds []string

	for _, file := range files {
		fmt.Printf("  - %s", filepath.Base(file))

		f, err := excelize.OpenFile(file)
		if err != nil {
			fmt.Printf(" [%s]\n", t("ERRO ao abrir", "ERROR opening"))
			continue
		}

		sheets := f.GetSheetList()
		if len(sheets) == 0 {
			fmt.Printf(" [%s]\n", t("sem sheets", "no sheets"))
			f.Close()
			continue
		}

		rows, err := f.GetRows(sheets[0])
		if err != nil {
			fmt.Printf(" [%s]\n", t("ERRO ao ler", "ERROR reading"))
			f.Close()
			continue
		}

		seedCount := 0
		for i, row := range rows {
			if i == 0 {
				continue
			}
			if len(row) >= 2 {
				seed := strings.TrimSpace(row[1])
				if seed != "" {
					words := strings.Fields(seed)
					if len(words) >= 12 {
						allSeeds = append(allSeeds, seed)
						seedCount++
					}
				}
			}
		}

		fmt.Printf(" -> %d seeds\n", seedCount)
		f.Close()
	}

	fmt.Println()
	fmt.Printf(t(
		"  Total de seeds importadas: %d\n",
		"  Total seeds imported: %d\n"), len(allSeeds))

	return allSeeds
}

// ============================================================================
// GERACAO DE RELATORIO EXCEL - 3 ABAS
// ============================================================================

func generateExcelReport(results []ScanResult) string {
	timestamp := time.Now().Format("20060102_150405")

	dirName := t(
		fmt.Sprintf("Resultados_%s", timestamp),
		fmt.Sprintf("Results_%s", timestamp))
	os.MkdirAll(dirName, 0755)

	fileName := t(
		fmt.Sprintf("Relatorio_Saldos_%s.xlsx", timestamp),
		fmt.Sprintf("Balance_Report_%s.xlsx", timestamp))
	filePath := filepath.Join(dirName, fileName)

	f := excelize.NewFile()

	// Headers com coluna Data Ultima Movimentacao
	headers := []string{
		t("Seed Phrase", "Seed Phrase"),
		t("Rede", "Network"),
		t("Derivacao", "Derivation"),
		t("Indice", "Index"),
		t("Endereco", "Address"),
		t("Saldo Nativo", "Native Balance"),
		t("Simbolo", "Symbol"),
		t("Tokens", "Tokens"),
		t("Historico", "History"),
		t("Qtd Transacoes", "Tx Count"),
		t("Data Ultima Movimentacao", "Last Transaction Date"),
		t("Chave Privada", "Private Key"),
	}

	// Estilo do header
	headerStyle, _ := f.NewStyle(&excelize.Style{
		Font:      &excelize.Font{Bold: true, Color: "FFFFFF", Size: 11},
		Fill:      excelize.Fill{Type: "pattern", Color: []string{"2F5496"}, Pattern: 1},
		Alignment: &excelize.Alignment{Horizontal: "center"},
		Border: []excelize.Border{
			{Type: "left", Color: "000000", Style: 1},
			{Type: "top", Color: "000000", Style: 1},
			{Type: "bottom", Color: "000000", Style: 1},
			{Type: "right", Color: "000000", Style: 1},
		},
	})

	balanceRowStyle, _ := f.NewStyle(&excelize.Style{
		Fill: excelize.Fill{Type: "pattern", Color: []string{"C6EFCE"}, Pattern: 1},
		Font: &excelize.Font{Bold: true},
	})

	historyRowStyle, _ := f.NewStyle(&excelize.Style{
		Fill: excelize.Fill{Type: "pattern", Color: []string{"FFF2CC"}, Pattern: 1},
	})

	colWidths := map[string]float64{
		"A": 40, "B": 15, "C": 22, "D": 8,
		"E": 50, "F": 20, "G": 8, "H": 40,
		"I": 10, "J": 14, "K": 24, "L": 70,
	}

	// ====== ABA 1: RESUMO (todos os resultados) ======
	summarySheet := t("Resumo", "Summary")
	f.SetSheetName("Sheet1", summarySheet)
	writeSheetHeaders(f, summarySheet, headers, headerStyle)
	writeSheetData(f, summarySheet, results, 2, balanceRowStyle, historyRowStyle, false, false)
	for col, width := range colWidths {
		f.SetColWidth(summarySheet, col, col, width)
	}

	// ====== ABA 2: COM SALDO (apenas enderecos com saldo atual) ======
	balanceSheet := t("Com Saldo", "With Balance")
	f.NewSheet(balanceSheet)
	writeSheetHeaders(f, balanceSheet, headers, headerStyle)
	writeSheetData(f, balanceSheet, results, 2, balanceRowStyle, historyRowStyle, true, false)
	for col, width := range colWidths {
		f.SetColWidth(balanceSheet, col, col, width)
	}

	// ====== ABA 3: COM HISTORICO (enderecos com historico mas sem saldo atual) ======
	historySheet := t("Com Historico", "With History")
	f.NewSheet(historySheet)
	writeSheetHeaders(f, historySheet, headers, headerStyle)
	writeSheetData(f, historySheet, results, 2, balanceRowStyle, historyRowStyle, false, true)
	for col, width := range colWidths {
		f.SetColWidth(historySheet, col, col, width)
	}

	// Salvar
	if err := f.SaveAs(filePath); err != nil {
		fmt.Printf(t(
			"  [!] Erro ao salvar Excel: %v\n",
			"  [!] Error saving Excel: %v\n"), err)
		return ""
	}

	return filePath
}

func writeSheetHeaders(f *excelize.File, sheet string, headers []string, style int) {
	for i, h := range headers {
		cell := fmt.Sprintf("%c1", 'A'+i)
		f.SetCellValue(sheet, cell, h)
	}
	f.SetCellStyle(sheet, "A1", fmt.Sprintf("%c1", 'A'+len(headers)-1), style)
}

func writeSheetData(f *excelize.File, sheet string, results []ScanResult, startRow int, balStyle int, histStyle int, onlyBalance bool, onlyHistory bool) {
	row := startRow
	for _, r := range results {
		// Filtrar conforme a aba
		if onlyBalance && !r.HasBalance {
			continue
		}
		if onlyHistory && (!r.HasHistory || r.HasBalance) {
			// Aba "Com Historico" = tem historico mas NAO tem saldo atual
			continue
		}

		tokenStr := ""
		for _, tok := range r.Tokens {
			if tokenStr != "" {
				tokenStr += " | "
			}
			tokenStr += fmt.Sprintf("%s: %s", tok.Symbol, tok.Balance)
		}

		historyStr := t("Nao", "No")
		if r.HasHistory {
			historyStr = t("Sim", "Yes")
		}

		lastTxDate := r.LastTxDate
		if lastTxDate == "" {
			lastTxDate = "-"
		}

		txCountStr := "-"
		if r.TxCount > 0 {
			txCountStr = fmt.Sprintf("%d", r.TxCount)
		}

		f.SetCellValue(sheet, fmt.Sprintf("A%d", row), r.SeedPhrase)
		f.SetCellValue(sheet, fmt.Sprintf("B%d", row), r.Network)
		f.SetCellValue(sheet, fmt.Sprintf("C%d", row), r.DerivationPath)
		f.SetCellValue(sheet, fmt.Sprintf("D%d", row), r.Index)
		f.SetCellValue(sheet, fmt.Sprintf("E%d", row), r.Address)
		f.SetCellValue(sheet, fmt.Sprintf("F%d", row), r.NativeBalance)
		f.SetCellValue(sheet, fmt.Sprintf("G%d", row), r.NativeSymbol)
		f.SetCellValue(sheet, fmt.Sprintf("H%d", row), tokenStr)
		f.SetCellValue(sheet, fmt.Sprintf("I%d", row), historyStr)
		f.SetCellValue(sheet, fmt.Sprintf("J%d", row), txCountStr)
		f.SetCellValue(sheet, fmt.Sprintf("K%d", row), lastTxDate)
		f.SetCellValue(sheet, fmt.Sprintf("L%d", row), r.PrivateKey)

		// Destacar linhas
		if r.HasBalance {
			f.SetCellStyle(sheet, fmt.Sprintf("A%d", row), fmt.Sprintf("L%d", row), balStyle)
		} else if r.HasHistory {
			f.SetCellStyle(sheet, fmt.Sprintf("A%d", row), fmt.Sprintf("L%d", row), histStyle)
		}

		row++
	}
}
